### PR TITLE
Updated the audit report 

### PR DESCRIPTION
**Pull request by banhday**
- Added a discussion between the Python KZG Specification and the pseudocodes in the KZG paper.
- Added small changes in other places.

### CODE REVIEW

**Comment by b13decker** [comment]
@saltiniroberto @banhday Do one of you have time to look at my suggestions and either accept or reject them? That way we can get this PR closed out. Thanks!

**Comment by saltiniroberto** [comment]
@b13decker 
I cannot find your suggestions anywhere. What am I missing?

**Comment by b13decker** [comment]
> @b13decker I cannot find your suggestions anywhere. What am I missing?

They are on the threads here. GitHub just doesn't allow me to accept my own suggestions 😆

**Review by b13decker — CHANGES_REQUESTED** [review]

**Comment by b13decker** [comment]
@saltiniroberto This was me being stupid and not realizing I hadn't submitted the review 🫤

**Review by b13decker — APPROVED** [review]

**Pull request merged**
